# Generated by Django 4.0.4 on 2022-12-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_staff_leave_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='data',
            new_name='date',
        ),
    ]
