# Generated by Django 4.0.4 on 2023-01-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_student_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_leave',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student_leave',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
